sudo: true
dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - docker build -f social/Dockerfile -t social .
      - docker images
      - docker tag latest $DOCKER_USERNAME/social
      - docker push $DOCKER_USERNAME/social

      - docker build -f bot-kafka/Dockerfile -t bot-kafka .
      - docker images
      - docker tag latest $DOCKER_USERNAME/bot-kafka
      - docker push $DOCKER_USERNAME/bot-kafka

      - docker build -f messenger/Dockerfile -t messenger .
      - docker images
      - docker tag latest $DOCKER_USERNAME/messenger
      - docker push $DOCKER_USERNAME/messenger

      - docker build -f twitter/Dockerfile -t twitter .
      - docker images
      - docker tag latest $DOCKER_USERNAME/twitter
      - docker push $DOCKER_USERNAME/twitter
#    - stage: delpoy to digital ocean
#      script:
#      - bash scripts/deploy.sh