sudo: true
dist: trusty
#
language: java
jdk: oraclejdk8

services:
  - docker

deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/twitter
  - docker push $DOCKER_USERNAME/messenger