sudo: true
dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t social/social .
      - docker images
      - docker tag social $DOCKER_USERNAME/social
      - docker push $DOCKER_USERNAME/social

      - docker build -t bot-kafka/bot-kafka .
      - docker images
      - docker tag bot-kafka $DOCKER_USERNAME/bot-kafka
      - docker push $DOCKER_USERNAME/bot-kafka

      - docker build -t messenger/messenger .
      - docker images
      - docker tag messenger $DOCKER_USERNAME/messenger
      - docker push $DOCKER_USERNAME/messenger

      - docker build -t twitter/twitter .
      - docker images
      - docker tag twitter $DOCKER_USERNAME/twitter
      - docker push $DOCKER_USERNAME/twitter
#    - stage: delpoy to digital ocean
#      script:
#      - bash scripts/deploy.sh