sudo: true
dist: trusty
#
language: java
jdk: oraclejdk8

services:
  - docker

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
  # deploy snapshots to Maven central, but only from master branch
  - mvn --settings docker-setting.xml -DskipTests -B deploy"