version: "2"

services:
  mongo:
      image: mongo:3.2.4
      ports:
      - 27017:27017
      command: --smallfiles
      environment:
        MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      GROUP_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "tweet:1:1,analyse:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  kafka_manager:
        image: mzagar/kafka-manager-docker:1.3.3.4
        container_name: kafkamanager
        ports:
          - 9000:9000
        depends_on:
          - kafka
        environment:
          ZK_HOSTS: zookeeper:2181
