version: "2"

services:
  web:
    image: bobbbaich/messenger
    container_name: messenger
    ports:
      - 8888:8080
    working_dir: /app
    env_file:
        - web-variables.env
    depends_on:
      - kafka
      - mongo
      - twitter

  twitter:
    image: bobbbaich/twitter
    container_name: twitter
    ports:
      - 8891:8081
    working_dir: /app
    env_file:
        - web-variables.env
    depends_on:
      - kafka

  mongo:
      image: mongo:3.2.4
      ports:
      - 27017:27017
      command: --smallfiles
      environment:
        MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      GROUP_ID: 0
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      KAFKA_ADVERTISED_HOST_NAME: 104.236.53.32
      KAFKA_CREATE_TOPICS: "tweet:1:1,analyse:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  elk:
    depends_on:
      - web
      - twitter
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  kafka_manager:
    image: mzagar/kafka-manager-docker:1.3.3.4
    container_name: kafkamanager
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181