#'docker' profile configuration

##---Loggin Properties---
logging:
  level:
    org.springframework.web: INFO
    org.springframework.social: DEBUG
    org.springframework.security: INFO
    org.springframework.batch: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: ERROR
    org.springframework.boot.actuate.endpoint.mvc: ERROR
    com.bobbbaich: DEBUG
kafka:
  bootstrap-servers: "PLAINTEXT://${SERVER_IP}:9092"
