#'local' profile configuration
spring:
  social:
      twitter:
        app-id: 1TbklIzewbPjwqXwwvDohBXSd
        app-secret: R9xyjE0g7OUzZLBkVogLFwJaGzMIJ3Ab01i89gjdiGm51JCQuN
      facebook:
        app-id: 740743756119649
        app-secret: 2d6f7bfae3a55fbd05f05eb15e906d6d
  data:
      mongodb:
        uri: mongodb://127.0.0.1:27017
        database: social
messenger:
  appSecret: 1
  verifyToken: 1
  pageAccessToken: 1
kafka:
  bootstrap-servers: "localhost:9092"