sudo: true
dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t twitter .
      - docker images
      - docker tag twitter $DOCKER_USERNAME/twitter
      - docker push $DOCKER_USERNAME/twitter
#    - stage: delpoy to digital ocean
#      script:
#      - bash scripts/deploy.sh